/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package es.uvigo.esei.tfg.logica.daos.xml;

/**
 *
 * @author Saul
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.05 at 02:44:40 AM CET 
//

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for levelType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="levelType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="VR"/>
 *     &lt;enumeration value="U"/>
 *     &lt;enumeration value="P"/>
 *     &lt;enumeration value="VH"/>
 *     &lt;enumeration value="AC"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "levelType")
@XmlEnum(String.class)
public enum LevelType {

    @XmlEnumValue("VR") MuyRaro("Muy raro"),
    @XmlEnumValue("U")  Improbable("Improbable"),
    @XmlEnumValue("P")  Posible("Posible"),
    @XmlEnumValue("VH") Probable("Probable"),
    @XmlEnumValue("AC") PracticamenteSeguro("PrÃ¡cticamente seguro");

    private String value;

    private LevelType(String value) {
        this.value = value;
    }
    
    
    
    public String value() {
        return value;
    }

    public static LevelType fromValue(String v) {
        return valueOf(v);
    }

}

