/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package es.uvigo.esei.tfg.logica.daos.xml;

/**
 *
 * @author Saul
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.05 at 02:44:40 AM CET 
//

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dimensions" type="{}dimensionsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="classes" type="{}classesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="threats" type="{}threatsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="criteria" type="{}criteriaType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="threat-announcement" type="{}threatAnnouncementType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dimensions",
    "criteria",
    "classes",
    "threats",
    "threatAnnouncements"
})
@XmlRootElement(name = "magerit-extension")
public class MageritExtension {

    protected List<DimensionsType> dimensions;
    protected List<ClassesType> classes;
    protected List<ThreatsType> threats;
    protected List<CriteriaType> criteria;
    @XmlElement(name = "threat-announcement")
    protected List<ThreatAnnouncementType> threatAnnouncements;

    public List<DimensionsType> getDimensions() {
        return dimensions;
    }

    public void setDimensions(List<DimensionsType> dimensions) {
        this.dimensions = dimensions;
    }

    public List<ClassesType> getClasses() {
        return classes;
    }

    public void setClasses(List<ClassesType> classes) {
        this.classes = classes;
    }

    public List<ThreatsType> getThreats() {
        return threats;
    }

    public void setThreats(List<ThreatsType> threats) {
        this.threats = threats;
    }

    public List<CriteriaType> getCriteria() {
        return criteria;
    }

    public void setCriteria(List<CriteriaType> criteria) {
        this.criteria = criteria;
    }

    public List<ThreatAnnouncementType> getThreatAnnouncements() {
        return threatAnnouncements;
    }

    public void setThreatAnnouncements(List<ThreatAnnouncementType> threatAnnouncements) {
        this.threatAnnouncements = threatAnnouncements;
    }

}

