/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package es.uvigo.esei.tfg.logica.daos.xml;

/**
 *
 * @author Saul
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.05 at 02:44:40 AM CET 
//

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for threatType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="threatType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="threat" type="{}threatType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="code" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tho" type="{}threatOrigin" />
 *       &lt;attribute name="thc" type="{}threatCause" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "threatType", propOrder = {"name", "description", "dimensions", "classes", "subThreats"})
public class ThreatType {

    @XmlAttribute(name = "code", required = true)
    protected String code;
    
    @XmlAttribute(name = "tho")
    protected ThreatOrigin tho;

    @XmlAttribute(name = "thc")
    protected ThreatCause thc;

    @XmlElement(name = "name")
    String name;

    @XmlElement(name = "description")
    String description;

    @XmlElement(name = "threat")
    List<ThreatType> subThreats;
    
    // Anadido a MAGERIT (lista de etiquetas de dimensiones)    
    @XmlElement(name = "dimension", required = false)
    List<String> dimensions;

    // Anadido a MAGERIT (lista de etiquetas de activos)        
    @XmlElement(name = "class", required = false)
    List<String> classes;
    

    public ThreatType() {
    }

    public ThreatType(String code, String name, String description, ThreatOrigin tho, ThreatCause thc) {
        this.name = name;
        this.description = description;
        this.code = code;
        this.tho = tho;
        this.thc = thc;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<ThreatType> getSubThreats() {
        return subThreats;
    }

    public void setsubThreats(List<ThreatType> subThreats) {
        this.subThreats = subThreats;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public ThreatOrigin getTho() {
        return tho;
    }

    public void setTho(ThreatOrigin tho) {
        this.tho = tho;
    }

    public ThreatCause getThc() {
        return thc;
    }

    public void setThc(ThreatCause thc) {
        this.thc = thc;
    }

    public List<String> getDimensions() {
        return dimensions;
    }

    public void setDimensions(List<String> dimensions) {
        this.dimensions = dimensions;
    }

    public List<String> getClasses() {
        return classes;
    }

    public void setClasses(List<String> classes) {
        this.classes = classes;
    }

    
    
}

